FROM python:3.10

RUN apt-get update && apt-get install -y wget unzip curl

RUN pip install selenium webdriver-manager

RUN apt-get install -y chromium-browser

COPY tests/test_app.py /test_app.py

CMD ["python", "/test_app.py"]
